### ISSUE TITLE
Missing dependencies in recipe

### ISSUE THREAD

**Issue by joachimwolff** [conda-forge/hyperopt-feedstock#8]
Issue:
Your recipe misses two dependencies: lightgbm and scikit-learn.

To create the error: Install hyperopt via `conda install hyperopt -c conda-forge`

and use `algo=atpe.suggest` as a algorithm for fmin.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by PhilipMay** [comment]
Hey @joachimwolff ! Thanks for reporting.

These dependencies are optional in hyperopt. See here: https://github.com/hyperopt/hyperopt/blob/12b88138592f7f6ba64cf6d28d2bcc930f08bedc/hyperopt/atpe.py#L655

I would like to keep it this way and also do not want to add the packages as hard dependencies.

**Comment by joachimwolff** [comment]
Wasn't it the idea of conda to install a package and not to care about the dependencies anymore? If now a functionality is optional and leads to a crash in a software if a certain dependency is missing, it makes it all very difficult for shipping and deploying a software. 
If you really don't want to include it, and I don't see a real reason why two more dependencies hurt, I suggest you split the package in two: one with hyperopt and the second one with the optional feature that needs to be installed separately. But here it should be clear that this optional feature is not available in the first package. To have a package which is known to crash is just a bad practice; also the source code you show is against very basic PEPs and of bad practice: https://www.python.org/dev/peps/pep-0008/#imports  

Moreover, hyperopt lists three algorithms, `random`, `tpe` and `adaptive tpe` in their documentation: http://hyperopt.github.io/hyperopt/ This does not indicate one of them is optional; and therefore the conda package should support all three out-of-the-box.

**Comment by BastianZim** [comment]
Conda-forge only lists the mandatory dependencies as we currently have no way to specify optional ones in the meta.yaml. This needs to be enabled by conda-build.
One way is an additional output here for which I'd be happy to accept a PR. Otherwise, I'll close this issue as this is not a problem in conda-forge.
